name: IslandGenerator
version: ${project.version}
main: ch.mixin.islandgenerator.main.IslandGeneratorPlugin
api-version: 1.19
softdepend: [ HolographicDisplays, MixedCatastrophes ]

commands:
  mx-ig:
    description: The Root Command for IslandGenerator.
permissions:
  islandGenerator.generate:
    description: Island Generation and Regeneration.
    default: op
  islandGenerator.reload:
    description: Reload Plugin Resources.
    default: op
  islandGenerator.config:
    description: Manipulate Config.
    default: op
  islandGenerator.*:
    description: All IslandGenerator Permissions
    default: op
    children:
      islandGenerator.generate: true
      islandGenerator.reload: true
      islandGenerator.config: true